spring.application.name=rigg-ads-b
server.port=8080

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/riggads_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=****
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# JWT settings
jwt.secret=ThisIsJWTSecret
# 1 day in milliseconds
jwt.expiration-ms=86400000

#mail setup
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rigg.tech.ads@gmail.com
spring.mail.password=apjh ehfn feqr imqh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.test-connection=true

